"""Delete seats from reservations

Revision ID: 22ad617d42a9
Revises: 2af8b027e723
Create Date: 2025-01-29 16:24:48.761741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ad617d42a9'
down_revision: Union[str, None] = '2af8b027e723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
